version: '3.8'

services:
  app:
    image: node:20-alpine
    container_name: ${PROJECT_NAME:-nodejs-app}
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./html:/app
    networks:
      - dployr-network
    ports:
      - "${EXPOSED_PORT:-8003}:3000"
    environment:
      - TZ=Europe/Berlin
      - NODE_ENV=production
    command: sh -c "npm install && npm start"

networks:
  dployr-network:
    external: true
