version: '3.8'

services:
  app:
    image: node:20-alpine
    container_name: ${PROJECT_NAME:-nodejs-app}
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules  # Verhindert, dass lokale node_modules Ã¼berschrieben werden
    networks:
      - dployr-network
    ports:
      - "${EXPOSED_PORT:-8003}:${APP_PORT:-3000}"
    environment:
      - NODE_ENV=production
      - PORT=${APP_PORT:-3000}
      - TZ=Europe/Berlin
      # Datenbank
      - DB_HOST=dployr-mariadb
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    command: sh -c "npm install && npm start"

networks:
  dployr-network:
    external: true
