version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: ${PROJECT_NAME:-static-web}
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - deployr-network
    ports:
      - "${EXPOSED_PORT:-8001}:80"
    environment:
      - TZ=Europe/Berlin

networks:
  deployr-network:
    external: true
